### ISSUE TITLE
Error: 'undefined' is not a function for Socket._get

### ISSUE THREAD

**Issue by stefan-dimitrov** [wrakky/appengine-channel-api-stub#1]
I'm trying to follow the README examples, but in my tests calling
```js
var socket = goog.appengine.Socket._get(token);
```
causes error:
```
TypeError: 'undefined' is not a function (evaluating 'goog.appengine.Socket._get(token)')
```

I'm running my tests on Karma Jasmine with PhantomJS and I'm on a Linux machine.

**Comment by stefan-dimitrov** [comment]
Previously I installed the lib from bower.
I checked out the project and found a difference: the bower version is missing the `Socket._get` function definition.

**Comment by stefan-dimitrov** [comment]
I see that the `dist/channel-api.js` file does not have the changes from `src/channel-api.js`. And only the `dist` directory is available from the bower repo.

I think the `dist` directory needs to be updated to reflect the changes from `src`.

**Comment by wrakky** [comment]
Thanks a lot! I must have a made a final change and forgotten to rebuild - I think that probably means you are the first person who has (tried to) use it :)

**Comment by stefan-dimitrov** [comment]
You're welcome :)
I guess I am one of the first. From what I've seen so far, it looks like not many people are using the channel api in angular. And probably not writing tests for it.
